image: docker/compose:1.29.2

pipelines:
  default:
    - step:
        script:
          - printenv | grep PLUGIN_ >> .env
          - docker-compose up -d --build
          - sleep 1m
          - docker-compose run --rm plugin git clone ${PLUGIN_REPOSITORY} ${PLUGIN_NAME}
          - docker-compose run --rm cli sh /scripts/wordpress.sh
          - docker-compose run --rm cli [ -f ./wp-content/plugins/${PLUGIN_NAME}/tests/e2e/cli/cli.sh ] && sh ./wp-content/plugins/${PLUGIN_NAME}/tests/e2e/cli/cli.sh
          - echo "Tests for PB checkout run here"
          - docker-compose run e2e --record --key $PLUGIN_CYPRESS_KEY
          - echo "Switching to USM"
          - docker-compose run --rm cli sh ./wp-content/plugins/porterbuddy-for-woocommerce/tests/e2e/cli/checkout_template.sh new_universal_shipping
          - echo "Tests for PB USM run here"
        services:
          - docker
        caches:
          - docker