image: docker/compose:1.29.2

pipelines:
  default:
    - step:
        script:
          - printenv | grep PLUGIN_ >> .env
          - docker-compose up -d --build
          - docker-compose run --rm plugin init
          - docker-compose run --rm plugin remote add origin ${PLUGIN_REPOSITORY}
          - docker-compose run --rm plugin fetch
          - docker-compose run --rm plugin checkout origin/dev -ft
          - sleep 1m
          - docker-compose run --rm cli sh /scripts/wordpress.sh
          - docker-compose run --rm cli [ -f ./wp-content/plugins/${PLUGIN_NAME}/tests/e2e/cli/cli.sh ] && sh ./wp-content/plugins/${PLUGIN_NAME}/tests/e2e/cli/cli.sh
          - echo "Tests for PB checkout run here"
          - docker-compose run -v $BITBUCKET_CLONE_DIR/plugin/${PLUGIN_NAME}/tests/e2e:/e2e e2e --record --key $PLUGIN_CYPRESS_KEY
          - echo "Switching to USM"
          - docker-compose run --rm cli sh ./wp-content/plugins/${PLUGIN_NAME}/tests/e2e/cli/checkout_template.sh new_universal_shipping
          - echo "Tests for PB USM run here"
        services:
          - docker
        caches:
          - docker