version: '3.1'
services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - e2e-net
  plugin:
    image: alpine/git
    env_file:
      - ./.env
    user: root
    volumes:
      - ./plugin:/git
      - ./.ssh:/root/.ssh
  wordpress:
    links:
      - db
    env_file:
      - ./.env
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WP_TAG=${WP_VERSION}
    ports:
      - "8000:80"
    expose:
      - 8000
    restart: unless-stopped
    user: root
    volumes:
      - ./wordpress:/var/www/html
      - ./plugin/${PLUGIN_NAME}:/var/www/html/wp-content/plugins/${PLUGIN_NAME}
    networks:
      - e2e-net
  cli:
    image: wordpress:cli
    env_file:
      - ./.env
    depends_on:
      - db
      - wordpress
    user: root
    volumes:
      - ./wordpress:/var/www/html
      - ./scripts:/scripts
      - ./plugin:/plugin
    networks:
      - e2e-net
  e2e:
    image: cypress/included:3.4.0
    working_dir: /e2e
    depends_on:
      - wordpress
    links:
      - wordpress
    environment:
      - CYPRESS_baseUrl=http://wordpress
      - CYPRESS_PROJECT_ID=${PLUGIN_CYPRESS_PROJECT_ID}
#    volumes:
#      - ./plugin/${PLUGIN_NAME}/tests/e2e:/e2e
    networks:
      - e2e-net
volumes:
  db:
  wordpress:
  plugin:


networks:
  e2e-net:
    driver: bridge
