# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #  push:
  #    branches: [ master ]
  #  pull_request:
  #    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    env:
      PLUGIN_REPOSITORY: ${{ secrets.PLUGIN_REPOSITORY  }}
      PLUGIN_NAME: ${{ secrets.PLUGIN_NAME  }}
      PLUGIN_CYPRESS_KEY: ${{ secrets.PLUGIN_CYPRESS_KEY  }}
      PLUGIN_CYPRESS_PROJECT_ID: ${{ secrets.PLUGIN_CYPRESS_PROJECT_ID  }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout plugin
        run: |
          git clone ${PLUGIN_REPOSITORY} ./plugin/temp
          mkdir -p ./wordpress/wp-content/plugins/${PLUGIN_NAME}
          sudo chmod -R 777 ./wordpress/wp-content
          sudo cp -R ./plugin/temp/* ./wordpress/wp-content/plugins/${PLUGIN_NAME}
      - name: Docker up
        run: |
          docker-compose up -d --build
          docker-compose run --rm cli sh -c "/scripts/wait-for-it.sh db:3306"
      - name: Set up wordpress
        run: |
          docker-compose run --rm cli sh -c "mkdir ./wp-content/upgrade"
          docker-compose run --rm cli sh -c "chmod -R 777 ./wp-content/upgrade"
          docker-compose run --rm cli sh -c "/scripts/wordpress.sh"
          docker-compose run --rm cli [ -f ./wp-content/plugins/${PLUGIN_NAME}/tests/e2e/cli/cli.sh ] && sh ./wp-content/plugins/${PLUGIN_NAME}/tests/e2e/cli/cli.sh
#      - name: Set up wordpress
#        run: |
#          echo "Tests for PB checkout run here"
#          docker-compose run --workdir /wordpress/wp-content/plugins/${PLUGIN_NAME}/tests/e2e e2e --record --key $PLUGIN_CYPRESS_KEY
#          echo "Switching to USM"
#          docker-compose run --rm cli sh ./wp-content/plugins/${PLUGIN_NAME}/tests/e2e/cli/checkout_template.sh new_universal_shipping
#          echo "Tests for PB USM run here"
